Added a way of setting an implicit set to the compiler options.
google/shaderc pull request #1179
Opened 2021-04-07 15:42 UTC by AlvaroBarua

2021-04-07 15:44 UTC, AlvaroBarua commented
@googlebot I signed it!

2021-07-21 14:12 UTC, zoddicus commented
I just noticed that this never was reviewed.

@dneto0 when you get back to the office can you take a look at it?

2022-01-28 10:38 UTC, AlvaroBarua commented
Hi, just remembered I added this pull request. I was wondering if it was reviewed?

2022-07-04 15:32 UTC, dneto0 requested changes
I am skeptical that this works.

Also, there are no tests.

2022-07-04 15:32 UTC, dneto0 commented on libshaderc_util/include/libshaderc_util/compiler.h
> +    hlsl_explicit_bindings_[static_cast<int>(stage)].clear();
This interferes with the operation of SetHlslRegisterSetAndBindingForStage

Also, glslang only operates on these options in triples.
See https://github.com/KhronosGroup/glslang/blob/b2d2c9dd3d77c6adadff37309aa58a181bafc5f9/glslang/HLSL/hlslParseHelper.cpp#L6388

2024-04-30 17:38 UTC, closed without merging