glslc: main.cc: update help: debug info disclaimer
google/shaderc pull request #1193
Opened 2021-05-22 19:06 UTC by pavel-the-best

As it appears, the option -g actually has some effect now.

2021-05-22 19:08 UTC, pavel-the-best commented
@googlebot I signed it!

2021-05-23 01:02 UTC, zoddicus approved these changes

2021-05-23 18:32 UTC, zoddicus requested changes
Looking at the Kokoro failures, it is looks like there is a test, HelpParameters, that is dooing some sort of string matching against this. Can you please update those tests?

2021-05-23 19:51 UTC, pavel-the-best commented
Done

2021-05-23 20:03 UTC, pavel-the-best commented
@googlebot I signed it!

2021-05-24 16:47 UTC, zoddicus approved these changes

2021-05-24 16:47 UTC, merged